export default {

	BOROUGH_SELECTED: 'BOROUGH_SELECTED', 
	CLEAR_CURRENT_TURN: 'CLEAR_CURRENT_TURN', 
	NEW_CURRENT_TURN: 'NEW_CURRENT_TURN', 
	SET_GAME_STAGE: 'SET_GAME_STAGE', 
	SET_MAP_LAT_LNG: 'SET_MAP_LAT_LNG', 
	CHANGE_VIEW: 'CHANGE_VIEW'

}; 
