export default {

	BOROUGH_SELECTED: 'BOROUGH_SELECTED', 
	CAN_EVALUATE_ANSWER: 'CAN_EVALUATE_ANSWER', 
	CANNOT_EVALUATE_ANSWER: 'CANNOT_EVAULATE_ANSWER', 	
	CHANGE_VIEW: 'CHANGE_VIEW', 
	CLEAR_CURRENT_TURN: 'CLEAR_CURRENT_TURN',
	GAME_OVER: 'GAME_OVER',  
	NEW_CURRENT_TURN: 'NEW_CURRENT_TURN',
	RESTART_GAME: 'RESTART_GAME', 
	SAVE_TURN: 'SAVE_TURN',  
	SET_GAME_STAGE: 'SET_GAME_STAGE',
	SET_LOAD_STATE: 'SET_LOAD_STATE',  
	SET_MAP_LAT_LNG: 'SET_MAP_LAT_LNG' 

}; 
