export default {

	BOROUGH_SELECTED: 'BOROUGH_SELECTED', 
	CAN_EVALUATE_ANSWER: 'CAN_EVALUATE_ANSWER', 
	CANNOT_EVALUATE_ANSWER: 'CANNOT_EVAULATE_ANSWER', 	 
	CLEAR_CURRENT_TURN: 'CLEAR_CURRENT_TURN',
	GAME_OVER: 'GAME_OVER',  
	INCREMENT_TOTAL_ROUNDS: 'INCREMENT_TOTAL_ROUNDS', 
	NEXT_TURN: 'NEXT_TURN',
	RESTART_GAME: 'RESTART_GAME', 
	SAVE_TURN: 'SAVE_TURN',  
	SET_GAME_STAGE: 'SET_GAME_STAGE',
	SET_LOAD_STATE: 'SET_LOAD_STATE', 
	SET_TURN_LOCATION_DATA: 'SET_TURN_LOCATION_DATA', 
	SHOW_MAP: 'SHOW_MAP', 
	SHOW_PANORAMA: 'SHOW_PANORAMA', 
	START_GAME: 'START_GAME'

}; 
