const events = {

	CORRECT_BOROUGH 	: 'CORRECT_BOROUGH', 
	GAME_COMPONENTS 	: 'GAME_COMPONENTS', 
	GAME_STAGE 			: 'GAME_STAGE', 
	HOST_LOCATION_DATA 	: 'HOST_LOCATION_DATA', 
	INCORRECT_BOROUGH 	: 'INCORRECT_BOROUGH', 
	NEXT_TURN 			: 'NEXT_TURN',
	RANDOM_LOCATION 	: 'RANDOM_LOCATION', 
	VIEW_CHANGE 		: 'VIEW_CHANGE'

}; 

export default events; 
