const events = {

	ANSWER_EVALUATED 	: 'ANSWER_EVALUATED', 
	CORRECT_BOROUGH 	: 'CORRECT_BOROUGH', 
	FINAL_ANSWER		: 'FINAL_ANSWER', 
	GAME_OVER 			: 'GAME_OVER',  
	GAME_STAGE 			: 'GAME_STAGE', 
	GEO_JSON_LOADED 	: 'GEO_JSON_LOADED', 
	GUESSING_LOCATION	: 'GUESSING_LOCATION', 
	HOST_LOCATION_DATA 	: 'HOST_LOCATION_DATA', 
	INCORRECT_BOROUGH 	: 'INCORRECT_BOROUGH', 
	INIT 				: 'INIT',
	NEW_PANORAMA	 	: 'NEW_PANORAMA',
	NEXT_TURN 			: 'NEXT_TURN',
	RESTART_GAME 		: 'RESTART_GAME', 
	SHOWING_PANORAMA 	: 'SHOWING_PANORAMA', 
	TURN_COMPLETE 		: 'TURN_COMPLETE',  
	VIEW_CHANGE 		: 'VIEW_CHANGE', 
	VIEW_COMPLETE		: 'VIEW_COMPLETE'

}; 

export default events; 
