export default {
	PREGAME: 'PREGAME', 
	LOADING_PANORAMA: 'LOADING_PANORAMA', 
	SHOWING_PANORAMA: 'SHOWING_PANORAMA', 
	GUESSING_LOCATION: 'GUESSING_LOCATION', 
	EVALUATING_ANSWER: 'EVALUATING_ANSWER', 
	POSTGAME: 'POSTGAME'
}; 
